#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/cfg{/log/nginx,/log/rtorrent,/log/rutorrent,/nginx,/php,/rtorrent/rtorrent_sess,/rutorrent/settings/users} \
	/cfg/rutorrent/profiles{/settings,/torrents,/users,/tmp} \
	/t{/completed,/downloading,/watch} \
	/run{/nginx,/php} \
	/var/lib/nginx/tmp/client_body

# copy config
PREV_DIR=$(pwd)

cd /defaults/rutorrent-conf || exit
	shopt -s globstar nullglob
	for i in *
	do
		[[ ! -e "/cfg/rutorrent/settings/${i}" ]] && cp -v "${i}" "/cfg/rutorrent/settings/${i}"
	done

cd "${PREV_DIR}" || exit

[[ ! -e /cfg/nginx/nginx.conf ]] && \
	cp /defaults/nginx.conf /cfg/nginx/nginx.conf


[[ ! -e /cfg/rtorrent/rtorrent.rc ]] && \
	cp /defaults/rtorrent.rc /cfg/rtorrent/rtorrent.rc
cp -pr /cfg/rutorrent/settings/* /usr/share/webapps/rutorrent/conf/

if [ ! -e "/cfg/php/php.ini" ]; then
	cp /etc/php7/php.ini /cfg/php/php.ini
	sed -i -e 's/\(register_argc_argv .*=\).*/\1 On/g' /cfg/php/php.ini
fi

cp /cfg/php/php.ini /etc/php7/php.ini

# create symlink for webui files
[[ ! -e /var/www/localhost/rutorrent ]] && ln -s \
/usr/share/webapps/rutorrent /var/www/localhost/rutorrent

# delete lock file if exists
[[ -e /cfg/rtorrent/rtorrent_sess/rtorrent.lock ]] && \
	rm /cfg/rtorrent/rtorrent_sess/rtorrent.lock

# permissions
chown abc:abc \
	/t \
	/t{/completed,/downloading,/watch}

chown -R abc:abc \
	/cfg \
	/run \
	/usr/share/webapps/rutorrent \
	/var/lib/nginx \
	/var/www/localhost/rutorrent

chmod -R 755 /cfg/rutorrent/profiles
chmod 644 /etc/logrotate.d/*
