#!/usr/bin/with-contenv bash

# create .autodl config dir and link
[[ ! -d /cfg/.autodl ]] && (mkdir /cfg/.autodl && chown -R abc:abc /cfg/.autodl)
[[ ! -d /home/abc ]] && (mkdir /home/abc && chown -R abc:abc /home/abc)

# get rutorrent plugin
[[ ! -d /usr/share/webapps/rutorrent/plugins/autodl-rutorrent/.git ]] && (git clone https://github.com/autodl-community/autodl-rutorrent.git /usr/share/webapps/rutorrent/plugins/autodl-rutorrent && \
chown -R abc:abc /usr/share/webapps/rutorrent/plugins/autodl-rutorrent/)

# get autodl script for irssi
[[ ! -d /cfg/.irssi/scripts/.git ]] && (mkdir -p /cfg/.irssi/scripts && \
  git clone https://github.com/autodl-community/autodl-irssi.git /cfg/.irssi/scripts && \
  mkdir /cfg/.irssi/scripts/autorun && \
  ln -s /cfg/.irssi/scripts/autodl-irssi.pl /cfg/.irssi/scripts/autorun/autodl-irssi.pl && \
  chown -R abc:abc /config/.irssi )

# get updated trackers for irssi-autodl
wget --quiet -O /tmp/trackers.zip https://github.com/autodl-community/autodl-trackers/archive/master.zip && \
cd /cfg/.irssi/scripts/AutodlIrssi/trackers && \
unzip -q -o -j /tmp/trackers.zip && \
rm /tmp/trackers.zip

# update rutorrent plugin
cd /usr/share/webapps/rutorrent/plugins/autodl-rutorrent/ || exit
git pull
chown -R abc:abc /usr/share/webapps/rutorrent/plugins/autodl-rutorrent

# make sure perl is in irssi startup
echo "load perl" > /cfg/.irssi/startup

# symlink autodl/irssi folders to root
ln -s /cfg/.autodl /root/.autodl
ln -s /cfg/.irssi /root/.irssi
chown -R abc:abc /root/.autodl
chown -R abc:abc /root/.irssi

# update autodl script for irssi
cd /cfg/.irssi/scripts || exit
git pull
chown -R abc:abc /cfg/.irssi
