version: '2'

services:

  deluge:
    image: strues/deluge
    user: "1000:1000"
    ports:
    - "8080:8080"
    - "53160:53160"
    - "58846:58846"
    environment:
      WEB_PORT: 8080
    networks:
      - sb
    volumes_from:
      - volumes_data
  rutorrent:
    image: strues/rutorrent
    ports:
    - "8000:80"
    - "5000:5000"
    - "51413:51413"
    - "6881:6881/udp"
    environment:
      - WEB_PORT=8080
      - PGID=1000
      - PUID=1000
      - TZ="America/Denver"
    networks:
      - sb
    volumes_from:
      - volumes_data

  volumes_data:
      image: tianon/true
      volumes:
          - "./config/deluge:/config"
          - "./config/rtorrent:/cfg"
          - "./data:/downloads"
          - "./data:/t"

networks:
  sb:
    driver: bridge
